# MiniDispatcherServlet 在应用上下文未显式注册策略组件时使用的默认实现。
com.yrainy.web.servlet.HandlerMapping=com.yrainy.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
com.yrainy.web.servlet.HandlerAdapter=com.yrainy.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter
com.yrainy.web.servlet.HandlerExceptionResolver=com.yrainy.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver,com.yrainy.web.servlet.mvc.support.DefaultHandlerExceptionResolver
